### PR TITLE
Update appliances handler for AAM

### PR DESCRIPTION
**Pull request by jamesremuscat**
Building on work in several other branches, this PR extends the `cluster-appliances` handlers to function for both AAM and ASM.

Since both appliances now use the same method of configuring clusters (that is, by a JSON `POST` to a `/register` URL) and share the same architecture (using `alces-flight-www` as an HTTP(S) proxy), much of the code here is shared between the two.

I've also included the changes to create a section in the `alces-flight-www` resources page linking to the Access Manager webapp.

### CODE REVIEW

**Comment by mjtko** [comment]
Looks like this PR now needs a little attention before it can be merged.

**Comment by jamesremuscat** [comment]
Should merge happily now.

**Comment by mjtko** [comment]
Is there a good reason for the `clusters` rather than `access` hack? :)

**Comment by jamesremuscat** [comment]
Really, the variable is misnamed - rather than `appliance_type` it should rather be something like `appliance_resource_type`. I'm not sure if that's any clearer though...

Basically, the storage manager uses `/storage/` and the access manager uses `/clusters/` in the URL.

Would `appliance_resource_type` be clearer here? Or some other name?

**Comment by mjtko** [comment]
Thanks -- this is ok as it is for now I think.

I guess "clusters" makes more sense overall as the resource being mutated is a "cluster" rather than an "access" or a "storage".  Let's live with this for now and revisit later if we feel it needs changing.

**Pull request merged**
