### PR TITLE
Deny access to `alces customize pull` unless root

### PR DESCRIPTION
**Pull request by bobwhitelock**
Along with the supporting Clusterware PR (https://github.com/alces-software/clusterware/pull/222), this is a fix for https://github.com/alces-software/clusterware/issues/206.

### CODE REVIEW

**Comment by mjtko** [comment]
I think it might be better to use `process_reexec_sudo` rather than dying. Is there any reason you can think of why that might not be appropriate?

**Comment by bobwhitelock** [comment]
I think I assumed that it was a deliberate decision that `alces customize pull` should only be runnable by the `root` user of the cluster, so I made it so that they need to explicitly run it with `sudo` Is this not the case? Or does `process_reexec_sudo` still require you to be able to `sudo`? In either case then your way would be better.

**Comment by mjtko** [comment]
It's not easy to run `alces` under `sudo` as it's a shell function -- the `process_reexec_sudo` function performs the `sudo` in a clever way allowing users who have admin rights to transparently use the command.

**Comment by bobwhitelock** [comment]
OK, I'll make that change now.

**Comment by bobwhitelock** [comment]
Made that change above

**Comment by mjtko** [comment]
LGTM, thanks!

**Pull request merged**
